export type AppLocale = "zh" | "en";

export const appCopy = {
  zh: {
    tabDiscover: "发现",
    tabMessages: "消息",
    tabMoments: "动态",
    tabLearn: "练遇",
    tabMe: "我的",
    guestUser: "未注册用户",
    tierGuest: "游客（未注册）",
    tierLight: "轻账号（已注册）",
    tierVerified: "已真人认证",
    registerLogin: "注册 / 登录",
    langRegion: "语言与地区",
    uiLanguage: "界面语言",
    chineseVariants: "中文变体（可多选）",
    appearance: "外观主题",
    light: "浅色",
    dark: "深色",
    photoPrivacy: "照片可见范围",
    photoPrivacyHint: "控制谁能看到你的清晰照片。信任等级越高，可见范围越可收紧。",
    privacyPublic: "所有人可见",
    privacyPublicDesc: "包括未注册游客（默认，曝光最高）",
    privacyLoggedIn: "仅登录用户可见",
    privacyLoggedInDesc: "游客看到的是模糊图",
    privacyVerified: "仅认证用户可见",
    privacyVerifiedDesc: "最谨慎，只有通过真人认证的人能看",
    privacySecurity: "隐私与安全",
    phoneBound: "登录手机号",
    phoneBoundHint: "一号一账号",
    phoneBoundOk: "已绑定",
    phoneNeedLogin: "请用手机验证码登录 / 注册",
    emailBind: "绑定邮箱（可选）",
    emailBindHint: "用于找回与通知 · 绑定后需验证邮箱",
    comingSoon: "即将推出",
    blacklist: "黑名单 / 举报记录",
    membership: "会员订阅",
    signOut: "退出登录",
    resetDemo: "（演示）重置为游客状态",
    notifyTitle: "消息与通知",
    notifyPush: "开启消息推送",
    notifyPushDesc: "有新消息时弹出系统通知（需允许通知权限；添加到主屏幕后体验更好）",
    notifyBadge: "桌面角标",
    notifyBadgeDesc: "未读数量显示为红色角标（支持的手机/PWA 生效）",
    notifySound: "提示音",
    notifySoundDesc: "收到新消息时播放提示音",
    notifyDenied: "系统已拒绝通知权限，请到手机设置里打开",
    notifyOn: "已开启",
    notifyOff: "未开启",
    legalTitle: "条款与政策",
    terms: "用户协议",
    privacy: "隐私政策",
    authTitle: "手机号验证码登录",
    authHint: "一个手机号只能注册一个账号，防刷更干净。",
    authHintAction: (action: string) => `验证手机号即可${action}。`,
    getCode: "获取验证码",
    sending: "发送中…",
    emailOptional: "邮箱可在注册后于「我的 → 隐私与安全」中绑定（可选）",
    agreePrefix: "我已阅读并同意",
    agreeAnd: "与",
    agreeRequired: "请先勾选同意用户协议与隐私政策",
    enterOtp: "输入验证码",
  },
  en: {
    tabDiscover: "Discover",
    tabMessages: "Messages",
    tabMoments: "Moments",
    tabLearn: "Lianyu",
    tabMe: "Me",
    guestUser: "Guest",
    tierGuest: "Guest (not signed up)",
    tierLight: "Account (signed up)",
    tierVerified: "Verified",
    registerLogin: "Sign up / Log in",
    langRegion: "Language & region",
    uiLanguage: "App language",
    chineseVariants: "Chinese variants (multi-select)",
    appearance: "Appearance",
    light: "Light",
    dark: "Dark",
    photoPrivacy: "Who can see my photos",
    photoPrivacyHint:
      "Control who sees clear photos. Higher trust can mean tighter visibility.",
    privacyPublic: "Everyone",
    privacyPublicDesc: "Including guests (default, most exposure)",
    privacyLoggedIn: "Signed-in users only",
    privacyLoggedInDesc: "Guests see a blurred image",
    privacyVerified: "Verified users only",
    privacyVerifiedDesc: "Only users who passed selfie verification",
    privacySecurity: "Privacy & security",
    phoneBound: "Phone number",
    phoneBoundHint: "One phone, one account",
    phoneBoundOk: "Linked",
    phoneNeedLogin: "Sign in with phone OTP",
    emailBind: "Link email (optional)",
    emailBindHint: "Recovery & notices · verify after linking",
    comingSoon: "Coming soon",
    blacklist: "Blocklist / reports",
    membership: "Membership",
    signOut: "Sign out",
    resetDemo: "(Demo) Reset to guest",
    notifyTitle: "Messages & notifications",
    notifyPush: "Enable push notifications",
    notifyPushDesc:
      "System alerts for new messages (allow permission; best after Add to Home Screen)",
    notifyBadge: "App icon badge",
    notifyBadgeDesc: "Show unread count as a red badge when supported",
    notifySound: "Sound",
    notifySoundDesc: "Play a sound when a new message arrives",
    notifyDenied: "Notifications blocked — enable them in phone Settings",
    notifyOn: "On",
    notifyOff: "Off",
    legalTitle: "Legal",
    terms: "Terms of Use",
    privacy: "Privacy Policy",
    authTitle: "Phone OTP login",
    authHint: "One phone number can register only one account.",
    authHintAction: (action: string) => `Verify your phone to ${action}.`,
    getCode: "Get code",
    sending: "Sending…",
    emailOptional: "Email can be linked later in Me → Privacy & security",
    agreePrefix: "I have read and agree to the",
    agreeAnd: "and",
    agreeRequired: "Please agree to the Terms and Privacy Policy first",
    enterOtp: "Enter verification code",
  },
} as const;

export function tApp(locale: AppLocale) {
  return appCopy[locale === "en" ? "en" : "zh"];
}
