export type AppLocale = "zh" | "en";

export const appCopy = {
  zh: {
    tabDiscover: "发现",
    tabMessages: "消息",
    tabMoments: "动态",
    tabLearn: "练遇",
    tabMe: "我的",
    filterAll: "全部",
    filterCN: "🇨🇳 中国",
    filterUS: "🇺🇸 美国",
    filterOnline: "在线",
    syncing: "同步中…",
    guestUser: "未注册用户",
    tierGuest: "游客（未注册）",
    tierLight: "轻账号（已注册）",
    tierVerified: "已真人认证",
    registerLogin: "注册 / 登录",
    goVerify: "去认证",
    langRegion: "语言与地区",
    uiLanguage: "界面语言",
    chineseVariants: "中文变体（可多选）",
    appearance: "外观主题",
    light: "浅色",
    dark: "深色",
    photoPrivacy: "照片可见范围",
    photoPrivacyHint: "控制谁能看到你的清晰照片。信任等级越高，可见范围越可收紧。",
    privacyPublic: "所有人可见",
    privacyPublicDesc: "包括未注册游客（默认，曝光最高）",
    privacyLoggedIn: "仅登录用户可见",
    privacyLoggedInDesc: "游客看到的是模糊图",
    privacyVerified: "仅认证用户可见",
    privacyVerifiedDesc: "最谨慎，只有通过真人认证的人能看",
    privacySecurity: "隐私与安全",
    phoneBound: "登录手机号",
    phoneBoundHint: "一号一账号",
    phoneBoundOk: "已绑定",
    phoneNeedLogin: "请用邮箱或手机验证码登录 / 注册",
    emailBind: "绑定邮箱",
    emailBindHint: "用于找回、收据与通知 · 绑定后请查收确认邮件",
    emailBoundOk: "已绑定",
    emailBindAction: "发送确认邮件",
    emailBindPending: "已发送，请打开邮箱确认",
    emailBindPlaceholder: "name@example.com",
    comingSoon: "即将推出",
    blacklist: "黑名单 / 举报记录",
    membership: "会员订阅",
    signOut: "退出登录",
    resetDemo: "（演示）重置为游客状态",
    notifyTitle: "消息与通知",
    notifyPush: "开启消息推送",
    notifyPushDesc: "有新消息时弹出系统通知（需允许通知权限；添加到主屏幕后体验更好）",
    notifyBadge: "桌面角标",
    notifyBadgeDesc: "未读数量显示为红色角标（支持的手机/PWA 生效）",
    notifySound: "提示音",
    notifySoundDesc: "收到新消息时播放提示音",
    notifyDenied: "系统已拒绝通知权限，请到手机设置里打开",
    notifyOn: "已开启",
    notifyOff: "未开启",
    legalTitle: "条款与政策",
    terms: "用户协议",
    privacy: "隐私政策",
    authTitle: "登录 / 注册",
    authHint:
      "中国：邮箱验证码优先；美国：Google / Apple 或邮箱。手机短信开通后会自动出现。",
    authHintAction: (action: string) => `登录后即可${action}。`,
    authRegionCN: "中国",
    authRegionUS: "美国",
    continueApple: "通过 Apple 继续",
    continueGoogle: "通过 Google 继续",
    continueEmail: "邮箱验证码登录",
    continuePhone: "手机短信登录",
    continuePhoneBackup: "手机短信（备用 · 即将开通）",
    emailPlaceholder: "邮箱地址",
    getEmailCode: "发送邮箱验证码",
    cnSmsBackupHint:
      "手机短信备用通道即将开通。目前请使用邮箱验证码或 Apple 登录。",
    usSmsPendingHint:
      "美区暂以 Google / Apple / 邮箱为主；手机短信开通后会自动出现在这里。",
    orDivider: "或",
    getCode: "获取验证码",
    sending: "发送中…",
    verifying: "验证中…",
    verifyContinue: "验证并继续",
    changeEmail: "改邮箱",
    changePhone: "改号码",
    resendCode: "重新发送",
    resendIn: (s: number) => `${s}s 后重发`,
    emailOptional: "也可稍后在「我的 → 隐私与安全」绑定邮箱",
    demoOtpHint: "开发环境未接通短信时可用演示码",
    otpSentPhone: (masked: string, isNew: boolean) =>
      `已发送至 ${masked}${isNew ? " · 新账号" : " · 登录已有账号"}`,
    otpSentEmail: (email: string) => `验证码已发送至 ${email}`,
    agreePrefix: "我已阅读并同意",
    agreeAnd: "与",
    agreeRequired: "请先勾选同意用户协议与隐私政策",
    enterOtp: "输入验证码",
  },
  en: {
    tabDiscover: "Discover",
    tabMessages: "Messages",
    tabMoments: "Moments",
    tabLearn: "Lianyu",
    tabMe: "Me",
    filterAll: "All",
    filterCN: "🇨🇳 China",
    filterUS: "🇺🇸 USA",
    filterOnline: "Online",
    syncing: "Syncing…",
    guestUser: "Guest",
    tierGuest: "Guest (not signed up)",
    tierLight: "Account (signed up)",
    tierVerified: "Verified",
    registerLogin: "Sign up / Log in",
    goVerify: "Get verified",
    langRegion: "Language & region",
    uiLanguage: "App language",
    chineseVariants: "Chinese variants (multi-select)",
    appearance: "Appearance",
    light: "Light",
    dark: "Dark",
    photoPrivacy: "Who can see my photos",
    photoPrivacyHint:
      "Control who sees clear photos. Higher trust can mean tighter visibility.",
    privacyPublic: "Everyone",
    privacyPublicDesc: "Including guests (default, most exposure)",
    privacyLoggedIn: "Signed-in users only",
    privacyLoggedInDesc: "Guests see a blurred image",
    privacyVerified: "Verified users only",
    privacyVerifiedDesc: "Only users who passed selfie verification",
    privacySecurity: "Privacy & security",
    phoneBound: "Phone number",
    phoneBoundHint: "One phone, one account",
    phoneBoundOk: "Linked",
    phoneNeedLogin: "Sign in with email or phone OTP",
    emailBind: "Link email",
    emailBindHint: "Recovery, receipts & notices · confirm via email",
    emailBoundOk: "Linked",
    emailBindAction: "Send confirmation",
    emailBindPending: "Sent — check your inbox to confirm",
    emailBindPlaceholder: "name@example.com",
    comingSoon: "Coming soon",
    blacklist: "Blocklist / reports",
    membership: "Membership",
    signOut: "Sign out",
    resetDemo: "(Demo) Reset to guest",
    notifyTitle: "Messages & notifications",
    notifyPush: "Enable push notifications",
    notifyPushDesc:
      "System alerts for new messages (allow permission; best after Add to Home Screen)",
    notifyBadge: "App icon badge",
    notifyBadgeDesc: "Show unread count as a red badge when supported",
    notifySound: "Sound",
    notifySoundDesc: "Play a sound when a new message arrives",
    notifyDenied: "Notifications blocked — enable them in phone Settings",
    notifyOn: "On",
    notifyOff: "Off",
    legalTitle: "Legal",
    terms: "Terms of Use",
    privacy: "Privacy Policy",
    authTitle: "Sign up / Log in",
    authHint:
      "China: email code first. US: Google / Apple or email. Phone SMS will appear here once enabled.",
    authHintAction: (action: string) => `Sign in to ${action}.`,
    authRegionCN: "China",
    authRegionUS: "United States",
    continueApple: "Continue with Apple",
    continueGoogle: "Continue with Google",
    continueEmail: "Email code",
    continuePhone: "Phone SMS",
    continuePhoneBackup: "Phone SMS (backup · coming soon)",
    emailPlaceholder: "Email address",
    getEmailCode: "Send email code",
    cnSmsBackupHint:
      "SMS backup is coming soon. For now, please use email code or Apple.",
    usSmsPendingHint:
      "US sign-in is Google / Apple / email for now. Phone SMS will appear here once enabled.",
    orDivider: "or",
    getCode: "Get code",
    sending: "Sending…",
    verifying: "Verifying…",
    verifyContinue: "Verify & continue",
    changeEmail: "Change email",
    changePhone: "Change number",
    resendCode: "Resend",
    resendIn: (s: number) => `Resend in ${s}s`,
    emailOptional: "You can also link email later in Me → Privacy & security",
    demoOtpHint: "Dev demo code when SMS is not wired",
    otpSentPhone: (masked: string, isNew: boolean) =>
      `Sent to ${masked}${isNew ? " · new account" : " · existing account"}`,
    otpSentEmail: (email: string) => `Code sent to ${email}`,
    agreePrefix: "I have read and agree to the",
    agreeAnd: "and",
    agreeRequired: "Please agree to the Terms and Privacy Policy first",
    enterOtp: "Enter verification code",
  },
} as const;

export function tApp(locale: AppLocale) {
  return appCopy[locale === "en" ? "en" : "zh"];
}
