export type MarketingLocale = "zh" | "en";

export const marketingCopy = {
  zh: {
    brand: "TalkLov",
    slogan: "TalkLov — 你的中美语言搭子与交友平台",
    navHome: "首页",
    navFaq: "常见问题",
    navTerms: "用户条款",
    navPrivacy: "隐私政策",
    navDownload: "主屏幕",
    navOpenApp: "打开 App",
    navLogin: "登录",
    heroTitle: "练语言，遇见另一个世界的人",
    heroSub:
      "和美国 / 中国的母语者一对一练中英文。内置翻译与破冰，先逛逛感受合拍，聊天前真人认证。",
    ctaBrowse: "免费开始",
    ctaDownload: "添加到主屏幕",
    badge: "跨文化语言社交",
    howTitle: "三步开始",
    how1t: "浏览发现",
    how1d: "游客也能看完整资料与照片，感受合拍的人。",
    how2t: "邮箱或手机验证码注册",
    how2d: "想打招呼时再登录：中国可用邮箱验证码，美国可用手机短信；一号一账号更安全。",
    how3t: "真人认证后畅聊",
    how3d: "真人闪验通过后开始聊天，边聊边学、自然交友。",
    featuresTitle: "为中美搭子而生",
    f1t: "语言互补匹配",
    f1d: "母语与在学语言互相匹配，普通话 / 粤语可标注。",
    f2t: "聊天里练语言",
    f2d: "翻译、纠错、语音消息、AI 一键破冰，降低开口焦虑。",
    f3t: "安全优先",
    f3d: "开场白需对方接受、真人认证、反诈提示从第一天就在。",
    devicesTitle: "手机与平板都能用",
    devicesSub: "PWA 网页应用，打开就能用；也可添加到主屏幕像原生 App。",
    phoneCaption: "发现 · 资料卡",
    tabletCaption: "资料主页预览",
    downloadTitle: "添加到手机主屏幕",
    downloadSub: "网页版现已可用，添加到主屏幕即可像 App 一样使用；商店版本即将上线。",
    downloadWeb: "打开免下载版",
    downloadIos: "App Store（即将推出）",
    downloadAndroid: "Google Play（即将推出）",
    downloadHint: "",
    installIosTitle: "iPhone（Safari）",
    installIosSteps: [
      "点击当前右下角的「···」",
      "点击「分享」（有的机型显示为「共享」）",
      "选择「添加到主屏幕」并确认，即可在主屏幕找到 TalkLov 图标",
    ],
    installAndroidTitle: "安卓手机（含国内浏览器）",
    installAndroidSteps: [
      "点浏览器菜单「···」或「⋮」（多在右上角；华为/小米/OPPO/vivo/夸克/UC 等均可）",
      "找「添加到主屏幕 / 添加到桌面 / 安装应用 / 收藏到桌面」任一选项",
      "确认后，即可在主屏幕找到 TalkLov 图标（若在微信里打开，先点「···」→「在浏览器打开」）",
    ],
    faqTitle: "常见问题",
    faqMore: "查看全部问题",
    navPartners: "推广合作",
    partnersTitle: "推广 TalkLov，赚取佣金",
    partnersSub:
      "适合内容创作者、社群主理人与 KOL。分享专属链接，用户开通 VIP / Boost 后按成交金额分佣。",
    partnersHowTitle: "怎么合作",
    partnersHow1t: "申请专属码",
    partnersHow1d: "告诉我们平台与受众，我们开通推广码与结算邮箱。",
    partnersHow2t: "分享专属链接",
    partnersHow2d: "例如 talklov.com/?ref=你的码。用户打开后自动归因（约 90 天）。",
    partnersHow3t: "按成交结算",
    partnersHow3d: "默认首单约 20%、续费约 10%（大 V 可谈）。月结打款。",
    partnersCta: "申请成为推广伙伴",
    partnersMailNote: "邮件主题请写「TalkLov 推广合作」，并附上平台账号与粉丝量级。",
    partnersEmail: "partners@talklov.com",
    footerTagline: "你的中美语言搭子与交友平台",
    footerRights: "© TalkLov. All rights reserved.",
    langLabel: "界面语言",
  },
  en: {
    brand: "TalkLov",
    slogan: "TalkLov — Your US–China language partner & social platform",
    navHome: "Home",
    navFaq: "FAQ",
    navTerms: "Terms",
    navPrivacy: "Privacy",
    navDownload: "Home Screen",
    navOpenApp: "Open App",
    navLogin: "Log in",
    heroTitle: "Practice a language. Meet someone from another world.",
    heroSub:
      "One-to-one Mandarin & English with native speakers. Built-in translation and icebreakers. Browse first — verify before you chat.",
    ctaBrowse: "Start free",
    ctaDownload: "Add to Home Screen",
    badge: "Cross-cultural language social",
    howTitle: "Get started in 3 steps",
    how1t: "Discover",
    how1d: "Guests can browse full profiles and photos before signing up.",
    how2t: "Email or phone signup",
    how2d: "Sign in when you want to say hi — email code in China, SMS in the US. One phone number per account.",
    how3t: "Verify, then chat",
    how3d: "Flash Check unlocks chat. Learn while you talk, connect naturally.",
    featuresTitle: "Built for US ↔ China partners",
    f1t: "Complementary matching",
    f1d: "Match by native & learning languages. Mandarin / Cantonese tags supported.",
    f2t: "Learn inside chat",
    f2d: "Translation, corrections, voice notes, and AI icebreakers.",
    f3t: "Safety first",
    f3d: "Openers need acceptance, selfie verification, and scam alerts from day one.",
    devicesTitle: "Phone & tablet ready",
    devicesSub: "Works as a PWA in the browser — or add to your home screen.",
    phoneCaption: "Discover · profile cards",
    tabletCaption: "Profile preview",
    downloadTitle: "Add to Home Screen",
    downloadSub: "Web app is live — add it to your home screen for an app-like feel. Store builds coming soon.",
    downloadWeb: "Open no-download version",
    downloadIos: "App Store (coming soon)",
    downloadAndroid: "Google Play (coming soon)",
    downloadHint: "",
    installIosTitle: "iPhone (Safari)",
    installIosSteps: [
      "Tap the ··· button at the bottom-right",
      "Tap Share",
      "Choose “Add to Home Screen” — then find the TalkLov icon on your Home Screen",
    ],
    installAndroidTitle: "Android (any browser)",
    installAndroidSteps: [
      "Tap ··· or ⋮ in your browser menu (usually top-right)",
      "Choose “Add to Home screen”, “Install app”, or similar",
      "Confirm — then find the TalkLov icon (if opened in WeChat, first choose “Open in browser”)",
    ],
    faqTitle: "FAQ",
    faqMore: "See all FAQs",
    navPartners: "Partners",
    partnersTitle: "Promote TalkLov. Earn commission.",
    partnersSub:
      "For creators, community leads, and KOLs. Share your link — earn when people buy VIP or Boost.",
    partnersHowTitle: "How it works",
    partnersHow1t: "Get your code",
    partnersHow1d: "Tell us your channels and audience. We issue a referral code and payout email.",
    partnersHow2t: "Share your link",
    partnersHow2d: "Like talklov.com/?ref=yourcode. Attribution sticks for about 90 days.",
    partnersHow3t: "Get paid",
    partnersHow3d: "Default ~20% first purchase, ~10% renewals (negotiable for larger partners). Monthly payouts.",
    partnersCta: "Apply as a partner",
    partnersMailNote: "Use subject “TalkLov affiliate” and include your socials + audience size.",
    partnersEmail: "partners@talklov.com",
    footerTagline: "Your US–China language partner & social platform",
    footerRights: "© TalkLov. All rights reserved.",
    langLabel: "Language",
  },
} as const;

export const faqItems = {
  zh: [
    {
      q: "TalkLov 是什么？",
      a: "TalkLov 是面向中美用户的语言交换与交友平台：练习中英文的同时，认识合拍的语伴与朋友。",
    },
    {
      q: "一定要注册才能看吗？",
      a: "不用。游客可以浏览发现页和完整资料；只有在你想打招呼时才需要注册（中国可用邮箱验证码，美国可用 Google / 手机短信）。",
    },
    {
      q: "为什么要真人认证？",
      a: "进入聊天前需完成「闪验」：对着镜头做几个小动作，确认是真人本人，降低盗图与骗子风险。我们不强制上传证件。",
    },
    {
      q: "一个手机号能注册几个账号？",
      a: "只能一个。手机号一号一账号；邮箱登录也会绑定到同一套账号体系，用于减少刷号与虚假身份。",
    },
    {
      q: "支持普通话和粤语吗？",
      a: "支持。母语为中文时可复选普通话、粤语，方便找到合适口音的语伴。",
    },
    {
      q: "如何下载？",
      a: "目前推荐使用网页版，并「添加到主屏幕」。iOS / Android 商店版本即将上线。",
    },
  ],
  en: [
    {
      q: "What is TalkLov?",
      a: "TalkLov is a language-exchange and social app for people in the US and China — practice Mandarin or English while meeting compatible partners.",
    },
    {
      q: "Do I need an account to browse?",
      a: "No. Guests can explore Discover and full profiles. Sign up only when you want to say hi — email code in China, or Google / SMS in the US.",
    },
    {
      q: "Why verification?",
      a: "Before chatting we ask for Flash Check — a quick on-camera motion selfie — to confirm you’re a real person. We don’t require government ID for MVP.",
    },
    {
      q: "Can one phone create multiple accounts?",
      a: "No. One phone number maps to one account. Email sign-in uses the same account system to reduce spam and fake profiles.",
    },
    {
      q: "Mandarin and Cantonese?",
      a: "Yes. Chinese speakers can select Mandarin, Cantonese, or both.",
    },
    {
      q: "How do I download?",
      a: "Use the web app now and Add to Home Screen. App Store / Google Play builds are coming soon.",
    },
  ],
} as const;
