export type MarketingLocale = "zh" | "en";

export const marketingCopy = {
  zh: {
    brand: "TalkLov",
    slogan: "TalkLov — 你的中美语言搭子与交友平台",
    navHome: "首页",
    navFaq: "常见问题",
    navTerms: "用户条款",
    navPrivacy: "隐私政策",
    navDownload: "主屏幕",
    navOpenApp: "打开 App",
    navLogin: "登录",
    heroTitle: "练语言，遇见另一个世界的人",
    heroSub:
      "和美国 / 中国的母语者一对一练中英文。内置翻译与破冰，先逛逛感受合拍，聊天前真人认证。",
    ctaBrowse: "免费开始",
    ctaDownload: "添加到主屏幕",
    badge: "跨文化语言社交",
    howTitle: "三步开始",
    how1t: "浏览发现",
    how1d: "游客也能看完整资料与照片，感受合拍的人。",
    how2t: "手机验证码注册",
    how2d: "想打招呼时再用手机号验证，一号一账号更安全。",
    how3t: "真人认证后畅聊",
    how3d: "自拍活体通过后开始聊天，边聊边学、自然交友。",
    featuresTitle: "为中美搭子而生",
    f1t: "语言互补匹配",
    f1d: "母语与在学语言互相匹配，普通话 / 粤语可标注。",
    f2t: "聊天里练语言",
    f2d: "翻译、纠错、语音消息、AI 一键破冰，降低开口焦虑。",
    f3t: "安全优先",
    f3d: "开场白需对方接受、真人认证、反诈提示从第一天就在。",
    devicesTitle: "手机与平板都能用",
    devicesSub: "PWA 网页应用，打开就能用；也可添加到主屏幕像原生 App。",
    phoneCaption: "发现 · 资料卡",
    tabletCaption: "资料主页预览",
    downloadTitle: "添加到手机主屏幕",
    downloadSub: "网页版现已可用，添加到主屏幕即可像 App 一样使用；商店版本即将上线。",
    downloadWeb: "打开免下载版",
    downloadIos: "App Store（即将推出）",
    downloadAndroid: "Google Play（即将推出）",
    downloadHint: "",
    installIosTitle: "iPhone（Safari）",
    installIosSteps: [
      "点击当前右下角的「···」",
      "点击「分享」（有的机型显示为「共享」）",
      "选择「添加到主屏幕」并确认，即可在主屏幕找到 TalkLov 图标",
    ],
    installAndroidTitle: "安卓手机",
    installAndroidSteps: [
      "点击浏览器右上角的「···」或「⋮」",
      "选择「添加到主屏幕」或「安装应用」",
      "确认后，即可在主屏幕找到 TalkLov 图标",
    ],
    faqTitle: "常见问题",
    faqMore: "查看全部问题",
    footerTagline: "你的中美语言搭子与交友平台",
    footerRights: "© TalkLov. All rights reserved.",
    langLabel: "界面语言",
  },
  en: {
    brand: "TalkLov",
    slogan: "TalkLov — Your US–China language partner & social platform",
    navHome: "Home",
    navFaq: "FAQ",
    navTerms: "Terms",
    navPrivacy: "Privacy",
    navDownload: "Home Screen",
    navOpenApp: "Open App",
    navLogin: "Log in",
    heroTitle: "Practice a language. Meet someone from another world.",
    heroSub:
      "One-to-one Mandarin & English with native speakers. Built-in translation and icebreakers. Browse first — verify before you chat.",
    ctaBrowse: "Start free",
    ctaDownload: "Add to Home Screen",
    badge: "Cross-cultural language social",
    howTitle: "Get started in 3 steps",
    how1t: "Discover",
    how1d: "Guests can browse full profiles and photos before signing up.",
    how2t: "Phone OTP signup",
    how2d: "Register with SMS when you want to say hi — one phone, one account.",
    how3t: "Verify, then chat",
    how3d: "Selfie liveness unlocks chat. Learn while you talk, connect naturally.",
    featuresTitle: "Built for US ↔ China partners",
    f1t: "Complementary matching",
    f1d: "Match by native & learning languages. Mandarin / Cantonese tags supported.",
    f2t: "Learn inside chat",
    f2d: "Translation, corrections, voice notes, and AI icebreakers.",
    f3t: "Safety first",
    f3d: "Openers need acceptance, selfie verification, and scam alerts from day one.",
    devicesTitle: "Phone & tablet ready",
    devicesSub: "Works as a PWA in the browser — or add to your home screen.",
    phoneCaption: "Discover · profile cards",
    tabletCaption: "Profile preview",
    downloadTitle: "Add to Home Screen",
    downloadSub: "Web app is live — add it to your home screen for an app-like feel. Store builds coming soon.",
    downloadWeb: "Open no-download version",
    downloadIos: "App Store (coming soon)",
    downloadAndroid: "Google Play (coming soon)",
    downloadHint: "",
    installIosTitle: "iPhone (Safari)",
    installIosSteps: [
      "Tap the ··· button at the bottom-right",
      "Tap Share",
      "Choose “Add to Home Screen” — then find the TalkLov icon on your Home Screen",
    ],
    installAndroidTitle: "Android",
    installAndroidSteps: [
      "Tap ··· or ⋮ at the top-right of your browser",
      "Choose “Add to Home screen” or “Install app”",
      "Confirm — then find the TalkLov icon on your Home Screen",
    ],
    faqTitle: "FAQ",
    faqMore: "See all FAQs",
    footerTagline: "Your US–China language partner & social platform",
    footerRights: "© TalkLov. All rights reserved.",
    langLabel: "Language",
  },
} as const;

export const faqItems = {
  zh: [
    {
      q: "TalkLov 是什么？",
      a: "TalkLov 是面向中美用户的语言交换与交友平台：练习中英文的同时，认识合拍的语伴与朋友。",
    },
    {
      q: "一定要注册才能看吗？",
      a: "不用。游客可以浏览发现页和完整资料；只有在你想打招呼时才需要手机验证码注册。",
    },
    {
      q: "为什么要真人认证？",
      a: "进入聊天前需完成自拍活体检测，确认是真人本人，降低盗图与骗子风险。我们不强制上传证件。",
    },
    {
      q: "一个手机号能注册几个账号？",
      a: "只能一个。一号一账号，用于减少刷号与虚假身份。",
    },
    {
      q: "支持普通话和粤语吗？",
      a: "支持。母语为中文时可复选普通话、粤语，方便找到合适口音的语伴。",
    },
    {
      q: "如何下载？",
      a: "目前推荐使用网页版，并「添加到主屏幕」。iOS / Android 商店版本即将上线。",
    },
  ],
  en: [
    {
      q: "What is TalkLov?",
      a: "TalkLov is a language-exchange and social app for people in the US and China — practice Mandarin or English while meeting compatible partners.",
    },
    {
      q: "Do I need an account to browse?",
      a: "No. Guests can explore Discover and full profiles. Sign up with phone OTP only when you want to say hi.",
    },
    {
      q: "Why verification?",
      a: "Before chatting we ask for selfie liveness to confirm you’re a real person. We don’t require government ID for MVP.",
    },
    {
      q: "Can one phone create multiple accounts?",
      a: "No. One phone number maps to one account to reduce spam and fake profiles.",
    },
    {
      q: "Mandarin and Cantonese?",
      a: "Yes. Chinese speakers can select Mandarin, Cantonese, or both.",
    },
    {
      q: "How do I download?",
      a: "Use the web app now and Add to Home Screen. App Store / Google Play builds are coming soon.",
    },
  ],
} as const;
