import { Profile, ChatMessage } from "./types";

export const CURRENT_USER = {
  name: "You",
  gender: "male" as const,
  country: "US" as const,
};

const av = (id: string, n: 1 | 2 | 3 = 1) => `/avatars/${id}-${n}.png`;
const gal = (id: string, count: 1 | 2 | 3 = 1) =>
  Array.from({ length: count }, (_, i) => av(id, (i + 1) as 1 | 2 | 3));

/** ~30 diverse demo profiles — CN mostly women, US mostly men; mixed ages / looks. */
export const profiles: Profile[] = [
  // —— existing multi-photo ——
  {
    id: "lin",
    name: "林晓 Lin",
    age: 26,
    gender: "female",
    country: "CN",
    city: "上海 Shanghai",
    photo: av("lin", 1),
    photos: gal("lin", 3),
    nativeLang: "中文",
    learningLang: "English",
    level: "中级 Intermediate",
    intents: ["language", "friends"],
    interests: ["咖啡", "旅行", "摄影", "K-pop"],
    bio: "上海的产品经理，想练口语，也想认识世界各地有趣的人。周末喜欢逛展和拍照。",
    verified: true,
    online: true,
    photoPrivacy: "public",
    chineseVariants: ["mandarin"],
  },
  {
    id: "mei",
    name: "美琪 Maggie",
    age: 24,
    gender: "female",
    country: "CN",
    city: "成都 Chengdu",
    photo: av("mei", 1),
    photos: gal("mei", 3),
    nativeLang: "中文",
    learningLang: "English",
    level: "初级 Beginner",
    intents: ["language", "romance"],
    interests: ["火锅", "猫", "健身", "电影"],
    bio: "成都妹子，英语小白但很努力！想找耐心的语伴，也许还能遇到对的人 :)",
    verified: true,
    online: false,
    photoPrivacy: "public",
    chineseVariants: ["mandarin"],
  },
  {
    id: "jack",
    name: "Jack",
    age: 29,
    gender: "male",
    country: "US",
    city: "Austin, TX",
    photo: av("jack", 1),
    photos: gal("jack", 3),
    nativeLang: "English",
    learningLang: "中文",
    level: "HSK2",
    intents: ["language", "friends"],
    interests: ["篮球", "科技", "吉他", "旅行"],
    bio: "Software engineer learning Mandarin. 想去中国旅行，先把中文练好！",
    verified: true,
    online: true,
    photoPrivacy: "public",
  },
  {
    id: "yuki",
    name: "雨桐 Tina",
    age: 27,
    gender: "female",
    country: "CN",
    city: "北京 Beijing",
    photo: av("yuki", 1),
    photos: gal("yuki", 3),
    nativeLang: "中文",
    learningLang: "English",
    level: "高级 Advanced",
    intents: ["friends", "romance"],
    interests: ["爬山", "红酒", "读书", "创业"],
    bio: "北京，做设计。喜欢深度对话。English is my window to the world.",
    verified: true,
    online: true,
    photoPrivacy: "public",
    chineseVariants: ["mandarin"],
  },
  {
    id: "ryan",
    name: "Ryan",
    age: 31,
    gender: "male",
    country: "US",
    city: "Seattle, WA",
    photo: av("ryan", 1),
    photos: gal("ryan", 3),
    nativeLang: "English",
    learningLang: "中文",
    level: "HSK4",
    intents: ["language", "romance"],
    interests: ["徒步", "美食", "摄影", "历史"],
    bio: "Been to Chengdu twice — 想学好中文再回去。",
    verified: false,
    online: false,
    photoPrivacy: "public",
  },
  {
    id: "shan",
    name: "珊珊 Shan",
    age: 23,
    gender: "female",
    country: "CN",
    city: "广州 Guangzhou",
    photo: av("shan", 1),
    photos: gal("shan", 3),
    nativeLang: "中文",
    learningLang: "English",
    level: "中级 Intermediate",
    intents: ["language", "friends", "romance"],
    interests: ["奶茶", "追剧", "画画", "旅行"],
    bio: "广州女孩，粤语+普通话。想练英语顺便交外国朋友～",
    verified: true,
    online: true,
    photoPrivacy: "public",
    chineseVariants: ["cantonese", "mandarin"],
  },
  // —— new CN women ——
  {
    id: "jing",
    name: "静怡 Jing",
    age: 22,
    gender: "female",
    country: "CN",
    city: "杭州 Hangzhou",
    photo: av("jing"),
    photos: gal("jing"),
    nativeLang: "中文",
    learningLang: "English",
    level: "中级 Intermediate",
    intents: ["language", "friends"],
    interests: ["阅读", "咖啡", "独立电影"],
    bio: "大学生，戴眼镜爱泡图书馆。想找语伴聊书和日常。",
    verified: true,
    online: true,
    photoPrivacy: "public",
    chineseVariants: ["mandarin"],
  },
  {
    id: "wen",
    name: "文心 Wendy",
    age: 28,
    gender: "female",
    country: "CN",
    city: "上海 Shanghai",
    photo: av("wen"),
    photos: gal("wen"),
    nativeLang: "中文",
    learningLang: "English",
    level: "高级 Advanced",
    intents: ["friends", "romance"],
    interests: ["时装", "展览", "爵士乐"],
    bio: "品牌策划。周末喜欢外滩夜景和深度聊天。",
    verified: true,
    online: false,
    photoPrivacy: "public",
    chineseVariants: ["mandarin"],
  },
  {
    id: "hua",
    name: "花宁 Hua",
    age: 25,
    gender: "female",
    country: "CN",
    city: "苏州 Suzhou",
    photo: av("hua"),
    photos: gal("hua"),
    nativeLang: "中文",
    learningLang: "English",
    level: "中级 Intermediate",
    intents: ["language"],
    interests: ["园林", "茶", "水彩"],
    bio: "喜欢安静的对话和西湖边散步。求耐心语伴。",
    verified: false,
    online: true,
    photoPrivacy: "public",
    chineseVariants: ["mandarin"],
  },
  {
    id: "na",
    name: "娜娜 Nana",
    age: 30,
    gender: "female",
    country: "CN",
    city: "香港 Hong Kong",
    photo: av("na"),
    photos: gal("na"),
    nativeLang: "中文",
    learningLang: "English",
    level: "高级 Advanced",
    intents: ["language", "friends"],
    interests: ["金融", "跑步", "粤菜"],
    bio: "港漂金融人，粤语母语。想交认真练语言的朋友。",
    verified: true,
    online: true,
    photoPrivacy: "public",
    chineseVariants: ["cantonese", "mandarin"],
  },
  {
    id: "qian",
    name: "倩倩 Qian",
    age: 21,
    gender: "female",
    country: "CN",
    city: "深圳 Shenzhen",
    photo: av("qian"),
    photos: gal("qian"),
    nativeLang: "中文",
    learningLang: "English",
    level: "初级 Beginner",
    intents: ["language", "friends"],
    interests: ["二次元", "逛街", "桌游"],
    bio: "大三学生，英语还在打基础，但很爱聊天！",
    verified: true,
    online: true,
    photoPrivacy: "public",
    chineseVariants: ["mandarin"],
  },
  {
    id: "fang",
    name: "芳菲 Fang",
    age: 26,
    gender: "female",
    country: "CN",
    city: "厦门 Xiamen",
    photo: av("fang"),
    photos: gal("fang"),
    nativeLang: "中文",
    learningLang: "English",
    level: "中级 Intermediate",
    intents: ["language", "romance"],
    interests: ["瑜伽", "海边", "健康餐"],
    bio: "瑜伽教练，早起党。想用英语聊聊生活方式。",
    verified: true,
    online: false,
    photoPrivacy: "public",
    chineseVariants: ["mandarin"],
  },
  {
    id: "xue",
    name: "雪儿 Xue",
    age: 29,
    gender: "female",
    country: "CN",
    city: "南京 Nanjing",
    photo: av("xue"),
    photos: gal("xue"),
    nativeLang: "中文",
    learningLang: "English",
    level: "高级 Advanced",
    intents: ["friends"],
    interests: ["当代艺术", "黑胶", "写作"],
    bio: "美术馆工作人员。喜欢有品味、不油腻的交流。",
    verified: true,
    online: true,
    photoPrivacy: "public",
    chineseVariants: ["mandarin"],
  },
  {
    id: "lili",
    name: "莉莉 Lili",
    age: 24,
    gender: "female",
    country: "CN",
    city: "重庆 Chongqing",
    photo: av("lili"),
    photos: gal("lili"),
    nativeLang: "中文",
    learningLang: "English",
    level: "中级 Intermediate",
    intents: ["language", "friends", "romance"],
    interests: ["火锅", "爬山", "Vlog"],
    bio: "重庆崽儿，麻辣性格。Come try hotpot with me in English!",
    verified: false,
    online: true,
    photoPrivacy: "public",
    chineseVariants: ["mandarin"],
  },
  // —— CN men (少数穿插) ——
  {
    id: "wei",
    name: "伟杰 Wei",
    age: 27,
    gender: "male",
    country: "CN",
    city: "北京 Beijing",
    photo: av("wei"),
    photos: gal("wei"),
    nativeLang: "中文",
    learningLang: "English",
    level: "中级 Intermediate",
    intents: ["language", "friends"],
    interests: ["电竞", "篮球", "夜跑"],
    bio: "互联网产品。想练口语，聊科技和球赛都行。",
    verified: true,
    online: true,
    photoPrivacy: "public",
    chineseVariants: ["mandarin"],
  },
  {
    id: "hao",
    name: "浩然 Hao",
    age: 35,
    gender: "male",
    country: "CN",
    city: "西安 Xi'an",
    photo: av("hao"),
    photos: gal("hao"),
    nativeLang: "中文",
    learningLang: "English",
    level: "初级 Beginner",
    intents: ["language"],
    interests: ["历史", "书法", "旅行"],
    bio: "喜欢古城墙日落。英语慢热，但很真诚。",
    verified: true,
    online: false,
    photoPrivacy: "public",
    chineseVariants: ["mandarin"],
  },
  {
    id: "chen",
    name: "晨阳 Chen",
    age: 23,
    gender: "male",
    country: "CN",
    city: "南京 Nanjing",
    photo: av("chen"),
    photos: gal("chen"),
    nativeLang: "中文",
    learningLang: "English",
    level: "中级 Intermediate",
    intents: ["language", "friends"],
    interests: ["校园", "摄影", "民谣"],
    bio: "研究生，有点社恐，但线上聊天很积极～",
    verified: false,
    online: true,
    photoPrivacy: "public",
    chineseVariants: ["mandarin"],
  },
  // —— US men ——
  {
    id: "jake",
    name: "Jake",
    age: 28,
    gender: "male",
    country: "US",
    city: "San Diego, CA",
    photo: av("jake"),
    photos: gal("jake"),
    nativeLang: "English",
    learningLang: "中文",
    level: "HSK2",
    intents: ["language", "friends"],
    interests: ["冲浪", "牛仔", "中餐"],
    bio: "Beach guy learning Mandarin for a Shanghai trip.",
    verified: true,
    online: true,
    photoPrivacy: "public",
  },
  {
    id: "marcus",
    name: "Marcus",
    age: 31,
    gender: "male",
    country: "US",
    city: "Atlanta, GA",
    photo: av("marcus"),
    photos: gal("marcus"),
    nativeLang: "English",
    learningLang: "中文",
    level: "HSK3",
    intents: ["language", "romance"],
    interests: ["读书", "咖啡", "爵士"],
    bio: "Bookstore weekends. Looking for a patient Mandarin partner.",
    verified: true,
    online: true,
    photoPrivacy: "public",
  },
  {
    id: "diego",
    name: "Diego",
    age: 27,
    gender: "male",
    country: "US",
    city: "Miami, FL",
    photo: av("diego"),
    photos: gal("diego"),
    nativeLang: "English",
    learningLang: "中文",
    level: "HSK1",
    intents: ["language", "friends"],
    interests: ["天台日落", "拉丁舞", "街头小吃"],
    bio: "Spanglish + 一点点中文。Let's practice together!",
    verified: true,
    online: false,
    photoPrivacy: "public",
  },
  {
    id: "alex",
    name: "Alex",
    age: 33,
    gender: "male",
    country: "US",
    city: "New York, NY",
    photo: av("alex"),
    photos: gal("alex"),
    nativeLang: "English",
    learningLang: "中文",
    level: "HSK4",
    intents: ["friends", "romance"],
    interests: ["建筑", "博物馆", "红酒"],
    bio: "Product designer in NYC. Lived in Taipei for a summer.",
    verified: true,
    online: true,
    photoPrivacy: "public",
  },
  {
    id: "chris",
    name: "Chris",
    age: 26,
    gender: "male",
    country: "US",
    city: "Denver, CO",
    photo: av("chris"),
    photos: gal("chris"),
    nativeLang: "English",
    learningLang: "中文",
    level: "HSK2",
    intents: ["language", "friends"],
    interests: ["徒步", "滑雪", "露营"],
    bio: "Mountain weekends. Want to hike Huangshan someday.",
    verified: false,
    online: true,
    photoPrivacy: "public",
  },
  {
    id: "mike",
    name: "Mike",
    age: 28,
    gender: "male",
    country: "US",
    city: "Miami, FL",
    photo: av("mike"),
    photos: gal("mike"),
    nativeLang: "English",
    learningLang: "中文",
    level: "HSK2",
    intents: ["language"],
    interests: ["健身", "沙滩排球", "播客"],
    bio: "Trainer by day, tones practice by night 😅",
    verified: true,
    online: false,
    photoPrivacy: "public",
  },
  {
    id: "david",
    name: "David",
    age: 30,
    gender: "male",
    country: "US",
    city: "San Francisco, CA",
    photo: av("david"),
    photos: gal("david"),
    nativeLang: "English",
    learningLang: "中文",
    level: "HSK3",
    intents: ["language", "friends"],
    interests: ["创业", "粤语歌", "早茶"],
    bio: "ABC reconnecting with heritage Mandarin + Cantonese phrases.",
    verified: true,
    online: true,
    photoPrivacy: "public",
  },
  {
    id: "kevin",
    name: "Kevin",
    age: 34,
    gender: "male",
    country: "US",
    city: "Chicago, IL",
    photo: av("kevin"),
    photos: gal("kevin"),
    nativeLang: "English",
    learningLang: "中文",
    level: "HSK1",
    intents: ["language", "friends"],
    interests: ["独立音乐", "啤酒", "冬日湖边"],
    bio: "Beanie season forever. Slow Mandarin learner, fast laughs.",
    verified: false,
    online: true,
    photoPrivacy: "public",
  },
  {
    id: "tom",
    name: "Tom",
    age: 29,
    gender: "male",
    country: "US",
    city: "Boston, MA",
    photo: av("tom"),
    photos: gal("tom"),
    nativeLang: "English",
    learningLang: "中文",
    level: "HSK3",
    intents: ["language", "romance"],
    interests: ["图书馆", "板球", "印中美食"],
    bio: "Engineer who loves quiet cafés and careful tones.",
    verified: true,
    online: false,
    photoPrivacy: "public",
  },
  {
    id: "jordan",
    name: "Jordan",
    age: 25,
    gender: "male",
    country: "US",
    city: "Columbus, OH",
    photo: av("jordan"),
    photos: gal("jordan"),
    nativeLang: "English",
    learningLang: "中文",
    level: "HSK2",
    intents: ["language", "friends"],
    interests: ["大学篮球", "漫画", "路边摊"],
    bio: "College energy. Want a language buddy for daily chats.",
    verified: true,
    online: true,
    photoPrivacy: "public",
  },
  // —— US women (少数穿插) ——
  {
    id: "emma",
    name: "Emma",
    age: 27,
    gender: "female",
    country: "US",
    city: "Portland, OR",
    photo: av("emma"),
    photos: gal("emma"),
    nativeLang: "English",
    learningLang: "中文",
    level: "HSK3",
    intents: ["language", "friends"],
    interests: ["咖啡", "雨天", "陶艺"],
    bio: "Freckles & rainy windows. Learning Mandarin for a Kunming trip.",
    verified: true,
    online: true,
    photoPrivacy: "public",
  },
  {
    id: "ashley",
    name: "Ashley",
    age: 26,
    gender: "female",
    country: "US",
    city: "Brooklyn, NY",
    photo: av("ashley"),
    photos: gal("ashley"),
    nativeLang: "English",
    learningLang: "中文",
    level: "HSK2",
    intents: ["language", "romance"],
    interests: ["街舞", "布朗克斯美食", "播客"],
    bio: "Brooklyn stoop chats → Mandarin voice notes. Let's swap culture!",
    verified: true,
    online: false,
    photoPrivacy: "public",
  },
  {
    id: "sarah",
    name: "Sarah",
    age: 31,
    gender: "female",
    country: "US",
    city: "Seattle, WA",
    photo: av("sarah"),
    photos: gal("sarah"),
    nativeLang: "English",
    learningLang: "中文",
    level: "HSK4",
    intents: ["friends"],
    interests: ["医疗公益", "园艺", "纪录片"],
    bio: "Nurse learning Mandarin to help more patients' families.",
    verified: true,
    online: true,
    photoPrivacy: "public",
  },
];

export function getProfile(id: string) {
  return profiles.find((p) => p.id === id);
}

export const sampleChat: ChatMessage[] = [
  {
    id: "m1",
    fromMe: false,
    text: "Hi! I saw you like photography too 📷",
    translation: "嗨！看到你也喜欢摄影",
    time: "10:21",
  },
  {
    id: "m2",
    fromMe: true,
    text: "Yes! Do you shoot film or digital?",
    translation: "是的！你拍胶片还是数码？",
    time: "10:23",
  },
];
