import { Profile, ChatMessage } from "./types";

export const CURRENT_USER = {
  name: "You",
  gender: "male" as const,
  country: "US" as const,
};

const av = (id: string, n: 1 | 2 | 3) => `/avatars/${id}-${n}.png`;

export const profiles: Profile[] = [
  {
    id: "lin",
    name: "林晓 Lin",
    age: 26,
    gender: "female",
    country: "CN",
    city: "上海 Shanghai",
    photo: av("lin", 1),
    photos: [av("lin", 1), av("lin", 2), av("lin", 3)],
    nativeLang: "中文",
    learningLang: "English",
    level: "中级 Intermediate",
    intents: ["language", "friends"],
    interests: ["咖啡", "旅行", "摄影", "K-pop"],
    bio: "上海的产品经理，想练口语，也想认识世界各地有趣的人。周末喜欢逛展和拍照。",
    verified: true,
    online: true,
    photoPrivacy: "public",
    chineseVariants: ["mandarin"],
  },
  {
    id: "mei",
    name: "美琪 Maggie",
    age: 24,
    gender: "female",
    country: "CN",
    city: "成都 Chengdu",
    photo: av("mei", 1),
    photos: [av("mei", 1), av("mei", 2), av("mei", 3)],
    nativeLang: "中文",
    learningLang: "English",
    level: "初级 Beginner",
    intents: ["language", "romance"],
    interests: ["火锅", "猫", "健身", "电影"],
    bio: "成都妹子，英语小白但很努力！想找耐心的语伴，也许还能遇到对的人 :)",
    verified: true,
    online: false,
    photoPrivacy: "loggedIn",
    chineseVariants: ["mandarin"],
  },
  {
    id: "jack",
    name: "Jack",
    age: 29,
    gender: "male",
    country: "US",
    city: "Austin, TX",
    photo: av("jack", 1),
    photos: [av("jack", 1), av("jack", 2), av("jack", 3)],
    nativeLang: "English",
    learningLang: "中文",
    level: "HSK2",
    intents: ["language", "friends"],
    interests: ["篮球", "科技", "吉他", "旅行"],
    bio: "Software engineer learning Mandarin. 想去中国旅行，先把中文练好！Love good coffee and live music.",
    verified: true,
    online: true,
    photoPrivacy: "public",
  },
  {
    id: "yuki",
    name: "雨桐 Tina",
    age: 27,
    gender: "female",
    country: "CN",
    city: "北京 Beijing",
    photo: av("yuki", 1),
    photos: [av("yuki", 1), av("yuki", 2), av("yuki", 3)],
    nativeLang: "中文",
    learningLang: "English",
    level: "高级 Advanced",
    intents: ["friends", "romance"],
    interests: ["爬山", "红酒", "读书", "创业"],
    bio: "北京，做设计。喜欢深度对话，想认识价值观相近的人。English is my window to the world.",
    verified: true,
    online: true,
    photoPrivacy: "verified",
    chineseVariants: ["mandarin"],
  },
  {
    id: "ryan",
    name: "Ryan",
    age: 31,
    gender: "male",
    country: "US",
    city: "Seattle, WA",
    photo: av("ryan", 1),
    photos: [av("ryan", 1), av("ryan", 2), av("ryan", 3)],
    nativeLang: "English",
    learningLang: "中文",
    level: "HSK4",
    intents: ["language", "romance"],
    interests: ["徒步", "美食", "摄影", "历史"],
    bio: "Been to Chengdu twice — 想学好中文再回去。Looking for a language partner and maybe more.",
    verified: false,
    online: false,
    photoPrivacy: "public",
  },
  {
    id: "shan",
    name: "珊珊 Shan",
    age: 23,
    gender: "female",
    country: "CN",
    city: "广州 Guangzhou",
    photo: av("shan", 1),
    photos: [av("shan", 1), av("shan", 2), av("shan", 3)],
    nativeLang: "中文",
    learningLang: "English",
    level: "中级 Intermediate",
    intents: ["language", "friends", "romance"],
    interests: ["奶茶", "追剧", "画画", "旅行"],
    bio: "广州女孩，想练英语顺便交个外国朋友，看缘分啦～ 我说粤语也说普通话！Be nice and patient please!",
    verified: true,
    online: true,
    photoPrivacy: "public",
    chineseVariants: ["cantonese", "mandarin"],
  },
];

export function getProfile(id: string) {
  return profiles.find((p) => p.id === id);
}

export const sampleChat: ChatMessage[] = [
  {
    id: "m1",
    fromMe: false,
    text: "Hi! I saw you like photography too 📷",
    translation: "嗨！看到你也喜欢摄影",
    time: "10:21",
  },
  {
    id: "m2",
    fromMe: true,
    text: "Yes! Do you shoot film or digital?",
    translation: "是的！你拍胶片还是数码？",
    time: "10:23",
  },
];
